=== eqxBarboss/Java_lab3/src/main/resources/teamSchema.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://bsuir.by/teamSchema"
        xmlns:tns="http://bsuir.by/teamSchema">

    <element name="team">
        <complexType>
           <sequence>
               <element name="softwareProduct" type="tns:SoftwareProductType"/>
               <element name="teamLead" type="tns:TeamLeadType"/>
               <element name="developers" type="tns:DevelopersType"/>
               <element name="testers" type="tns:TestersType"/>
               <element name="businessAnalysts" type="tns:BusinessAnalystsType"/>
           </sequence>
        </complexType>
    </element>

    <simpleType name="PhoneNumberType">
        <restriction base="string">
            <pattern value="\([0-9]{2}\)-[0-9]{3}-[0-9]{2}-[0-9]{2}"/>
        </restriction>
    </simpleType>

    <complexType name="Entity">
        <attribute name="id" type="ID" use="required"/>
    </complexType>

    <complexType name="EmployeeType">
        <complexContent>
            <extension base="tns:Entity">
                <sequence>
                    <element name="name" type="string"/>
                    <element name="surname" type="string"/>
                    <element name="phoneNumber" type="tns:PhoneNumberType"/>
                </sequence>
            </extension>
        </complexContent>
    </complexType>

    <complexType name="DeveloperType">
        <complexContent>
            <extension base="tns:EmployeeType">
                <sequence>
                    <element name="favoriteGame" type="string"/>
                </sequence>
            </extension>
        </complexContent>
    </complexType>

    <complexType name="BusinessAnalystType">
        <complexContent>
            <extension base="tns:EmployeeType">
                <sequence>
                    <element name="nickName" type="string"/>
                </sequence>
            </extension>
        </complexContent>
    </complexType>

    <complexType name="TesterType">
        <complexContent>
            <extension base="tns:EmployeeType">
                <sequence>
                    <element name="testsWritten" type="positiveInteger"/>
                </sequence>
            </extension>
        </complexContent>
    </complexType>

    <complexType name="TeamLeadType">
        <complexContent>
            <extension base="tns:DeveloperType">
                <sequence>
                    <element name="motto" type="string"/>
                </sequence>
            </extension>
        </complexContent>
    </complexType>
    
    <complexType name="SoftwareProductType">
        <complexContent>
            <extension base="tns:Entity">
                <sequence>
                    <element name="customer" type="string"/>
                    <element name="title" type="string"/>
                </sequence>
            </extension>
        </complexContent>
    </complexType>
    
    <complexType name="DevelopersType">
        <sequence>
            <element name="developer" type="tns:DeveloperType" maxOccurs="unbounded"/>
        </sequence>
    </complexType>

    <complexType name="BusinessAnalystsType">
        <sequence>
            <element name="businessAnalyst" type="tns:BusinessAnalystType" maxOccurs="unbounded"/>
        </sequence>
    </complexType>

    <complexType name="TestersType">
        <sequence>
            <element name="tester" type="tns:TesterType" maxOccurs="unbounded"/>
        </sequence>
    </complexType>

</schema>

=== eqxBarboss/Java_lab3/src/main/resources/team.xml
<?xml version="1.0" encoding="UTF-8" ?>
<team:team xmlns:team="http://bsuir.by/teamSchema"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="http://bsuir.by/teamSchema teamSchema.xsd">

    <softwareProduct id="s1">
        <customer>Customer</customer>
        <title>Title</title>
    </softwareProduct>
    
    <teamLead id="tl1">
        <name>Jason</name>
        <surname>Born</surname>
        <phoneNumber>(29)-111-11-11</phoneNumber>
        <favoriteGame>CS:GO</favoriteGame>
        <motto>Do ur best</motto>
    </teamLead>

    <developers>

        <developer id="d1">
            <name>Adam</name>
            <surname>Born</surname>
            <phoneNumber>(44)-222-22-22</phoneNumber>
            <favoriteGame>Game</favoriteGame>
        </developer>

        <developer id="d2">
            <name>Mada</name>
            <surname>Nrob</surname>
            <phoneNumber>(44)-222-22-22</phoneNumber>
            <favoriteGame>Emag</favoriteGame>
        </developer>

    </developers>

    <testers>

        <tester id="t1">
            <name>Name</name>
            <surname>Surname</surname>
            <phoneNumber>(24)-111-11-11</phoneNumber>
            <testsWritten>12</testsWritten>
        </tester>

    </testers>

    <businessAnalysts>

        <businessAnalyst id="b1">
            <name>Aasd</name>
            <surname>ASDasd</surname>
            <phoneNumber>(22)-123-12-12</phoneNumber>
            <nickName>Poop</nickName>
        </businessAnalyst>

    </businessAnalysts>

</team:team>
